services:
    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0

    sylius.importer.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.country"
            - "@sylius.processor.countries"
            - "@sylius.importer.result"
        tags:
            - { name: sylius.importer, type: country, format: csv }


    sylius.importer.payment_methods.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.payment_method"
            - "@sylius.processor.payment_methods"
            - "@sylius.importer.result"
        tags:
            - { name: sylius.importer, type: payment_method, format: csv }

    sylius.importer.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
            - "@sylius.importer.result"
        tags:
            - { name: sylius.importer, type: tax_category, format: csv }
