services:
    sylius.exporter.spreadsheet_writer_factory:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\PortSpreadsheetWriterFactory

    sylius.exporter.spreadsheet_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\SpreadsheetWriter
        arguments:
            - '@sylius.exporter.spreadsheet_writer_factory'

    # Spreadsheet-Exporters
    sylius.exporter.countries.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: xlsx }

    sylius.exporter.orders.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.orders"
            - ["Number", "State", "Product_list" , "Total" ,  "Currency_code", "Checkout_completed_at", "Checkout_state", "Payment_state", "Shipping_state", "Token_value", "Gender", "Full_name", "Email", "Telephone", "Shipping_address", "Billing_address" , "Customer_ip", "Notes"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: xlsx }

    sylius.exporter.customers.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.customers"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.customer, format: xlsx }

     sylius.exporter.orders.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\OrderResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.orders"
            - [ "Number", "State",  "Order_Total","Total_After_Discount",   "Currency_code",  "Order_created_Date" , "Order_updated_Date", "Payment_state", "Shipping_state", "Product" , "Item_Price", "Item_Quantity", "Item_Total", "Customer_Id", "Full_name", "Email", "Gender", "Telephone", "Vendor_Id" , "Vendor_Name" , "Vendor_Email" , "provinceCode", "provinceName","Address_Street" ,"Shipping_Total", "First_Name" ,"Last_Name"  , "Phone_Number", "Promotion_ID", "Promotion_Name","Promotion_Description", "Promotion_Coupon_ID","Promotion_Coupon_Name", "Checkout_completed_at", "Checkout_state", "Shipping_state", "Token_value",   "Shipping_address", "Billing_address" , "Customer_ip", "Notes" ]
            - "@sylius.exporters_transformer_pool" # Optional
            - "@sylius.repository.order"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: xlsx }
        
    sylius.exporter.pluginpool.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - [ "@sylius.exporter.plugin.resource.orders" ]
            - [ "Number", "State", "Order_Total" , "Total_After_Discount",   "Currency_code",  "Order_created_Date","Order_updated_Date", "Payment_state" ,"Shipping_state","Product" , "Item_Price", "Item_Quantity", "Item_Total", "Customer_Id",  "Full_name", "Email", "Gender",  "Telephone", "Vendor_Id" , "Vendor_Name" , "Vendor_Email","provinceCode", "provinceName","Address_Street" ,"Shipping_Total" , "First_Name","Last_Name" ,"Phone_Number", "Promotion_ID", "Promotion_Name","Promotion_Description", "Promotion_Coupon_ID","Promotion_Coupon_Name",  "Checkout_completed_at", "Checkout_state",  "Token_value",  "Shipping_address", "Billing_address" , "Customer_ip", "Notes" ]
        
    sylius.exporter.plugin.resource.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\OrderResourcePlugin
        arguments:
            - "@sylius.repository.order"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"
            - "@sylius.service.address_concatenation"
            - "@sylius.exporter.orm.hydrator.orders"