services:
    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0

    sylius.importer.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\CountriesImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.factory.country"
            - "@sylius.repository.country"
            - "@sylius.manager.country"
        tags:
            - { name: sylius.importer, type: country, format: csv }

    sylius.importer.payment_methods.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\PaymentMethodsImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.factory.payment_method"
            - "@sylius.repository.payment_method"
            - "@sylius.manager.payment_method"
        tags:
            - { name: sylius.importer, type: payment_method, format: csv }

    sylius.importer.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\TaxCategoriesImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.factory.tax_category"
            - "@sylius.repository.tax_category"
            - "@sylius.manager.tax_category"
        tags:
            - { name: sylius.importer, type: tax_category, format: csv }
