services:
    sylius.factory.excel_reader:
        class: Port\Excel\ExcelReaderFactory
        arguments:
            - 1

    sylius.importer.countries.excel:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.excel_reader"
            - "@sylius.manager.country"
            - "@sylius.processor.countries"
        tags:
            - { name: sylius.importer, type: country, format: excel }

    sylius.importer.payment_methods.excel:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.excel_reader"
            - "@sylius.manager.payment_method"
            - "@sylius.processor.payment_methods"
        tags:
            - { name: sylius.importer, type: payment_method, format: excel }

    sylius.importer.tax_categories.excel:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.excel_reader"
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
        tags:
            - { name: sylius.importer, type: tax_category, format: excel }
