services:
    sylius.exporter.excel_writer_factory:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\PortExcelWriterFactory

    sylius.exporter.excel_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\ExcelWriter
        arguments:
            - '@sylius.exporter.excel_writer_factory'

    # Excel-Exporters
    sylius.exporter.countries.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.excel_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: xlsx }
