services:
    sylius.csv_writer:
        class: Port\Csv\CsvWriter
        arguments:
            - ','

    sylius.exporter.csv_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\CsvWriter
        arguments:
            - '@sylius.csv_writer'

    # CSV-Exporters
    sylius.exporter.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: csv }

    

    sylius.exporter.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.tax_categories"
            - ["Id", "Code" ,"Name", "Description"]
            - "@sylius.exporters_transformer_pool" # Optional
        tags:
            - { name: sylius.exporter, type: sylius.tax_category, format: csv }

    sylius.exporter.customers.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.customers"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.customer, format: csv }

    sylius.exporter.products.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ProductResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.products"
            - ['Code', 'Locale', 'Name', 'Description', 'Short_description', 'Meta_description', 'Meta_keywords', 'Main_taxon', 'Taxons', 'Channels', 'Enabled', 'Price']
            - "@sylius.service.attributes_code"
            - "@sylius.service.product_image_code"
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.product, format: csv }
