services:
    sylius.factory.spreadsheet_reader:
        class: Port\Spreadsheet\SpreadsheetReaderFactory
        arguments:
            - 1

    # Spreadsheet-Importers
    sylius.importer.countries.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.spreadsheet_reader"
            - "@sylius.manager.country"
            - "@sylius.processor.countries"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: country, format: xlsx }

    sylius.importer.customer_group.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.spreadsheet_reader"
            - "@sylius.manager.customer_group"
            - "@sylius.processor.customer_groups"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer_group, format: xlsx }

    sylius.importer.payment_methods.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.spreadsheet_reader"
            - "@sylius.manager.payment_method"
            - "@sylius.processor.payment_methods"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: payment_method, format: xlsx }

    sylius.importer.tax_categories.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.spreadsheet_reader"
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: tax_category, format: xlsx }

    sylius.importer.taxons.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.spreadsheet_reader"
            - "@sylius.manager.taxon"
            - "@sylius.processor.taxonomies"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: taxonomy, format: xlsx }
     sylius.exporter.orders.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\OrderResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.orders"
            - [ "Number", "State",  "Order_Total","Total_After_Discount",   "Currency_code",  "Order_created_Date" , "Order_updated_Date", "Payment_state", "Shipping_state", "Product" , "Item_Price", "Item_Quantity", "Item_Total", "Customer_Id", "Full_name", "Email", "Gender", "Telephone", "Vendor_Id" , "Vendor_Name" , "Vendor_Email" , "provinceCode", "provinceName","Address_Street" ,"Shipping_Total", "First_Name" ,"Last_Name"  , "Phone_Number", "Promotion_ID", "Promotion_Name","Promotion_Description", "Promotion_Coupon_ID","Promotion_Coupon_Name", "Checkout_completed_at", "Checkout_state", "Shipping_state", "Token_value",   "Shipping_address", "Billing_address" , "Customer_ip", "Notes" ]
            - "@sylius.exporters_transformer_pool" # Optional
            - "@sylius.repository.order"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: xlsx }
        
    sylius.exporter.pluginpool.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - [ "@sylius.exporter.plugin.resource.orders" ]
            - [ "Number", "State", "Order_Total" , "Total_After_Discount",   "Currency_code",  "Order_created_Date","Order_updated_Date", "Payment_state" ,"Shipping_state","Product" , "Item_Price", "Item_Quantity", "Item_Total", "Customer_Id",  "Full_name", "Email", "Gender",  "Telephone", "Vendor_Id" , "Vendor_Name" , "Vendor_Email","provinceCode", "provinceName","Address_Street" ,"Shipping_Total" , "First_Name","Last_Name" ,"Phone_Number", "Promotion_ID", "Promotion_Name","Promotion_Description", "Promotion_Coupon_ID","Promotion_Coupon_Name",  "Checkout_completed_at", "Checkout_state",  "Token_value",  "Shipping_address", "Billing_address" , "Customer_ip", "Notes" ]
        
    sylius.exporter.plugin.resource.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\OrderResourcePlugin
        arguments:
            - "@sylius.repository.order"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"
            - "@sylius.service.address_concatenation"
            - "@sylius.exporter.orm.hydrator.orders"
