services:
    sylius.csv_writer:
        class: Port\Csv\CsvWriter

    sylius.exporter.csv_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\CsvWriter
        arguments:
            - '@sylius.csv_writer'

    # CSV-Exporters
    sylius.exporter.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: csv }
