services:
    sylius.importers_registry:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterRegistry
        arguments:
            - FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterInterface
            - importer

    sylius.controller.import_data:
        class: FriendsOfSylius\SyliusImportExportPlugin\Controller\ImportDataController
        arguments:
            - "@sylius.importers_registry"
            - "@router"
            - "@session"